POST localhost:8080/m152/
Content-Type: application/json

{
"filename": "file-test",
  "base64ImageString": "ewiugwnp9rgunewugnesg"
}

###
PUT localhost:8080/m152/update/file-test-new/file-test
Content-Type: application/json

###
GET localhost:8080/m152/filename/file-test
Content-Type: application/json

###
DELETE localhost:8080/m152/delete/new filename
Content-Type: application/json

###
GET localhost:8080/m152/convert
Content-Type: application/json